object_type: global_settings
overrides:
    "xmla.auth.token.enabled": true
    "query.factless.ignoreIncidentalFilter": false
    "xmla.discover.properties.daxdialect": tabular
    "soap.xpress.enabled": true
    "atscale.host": engine
    
